# -*- coding: utf-8 -*-
"""user_input.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h5hcL5MGz59rW6glKXBmrGndOwE1xpH5

Instructions:
Create a new Python file and name it "user_input.py"
Use the input() function to ask the user for their name and store it in a variable called "name".
Use the input() function to ask the user for their age and store it in a variable called "age".
Use the input() function to ask the user for their location and store it in a variable called "location".
Print out a personalized message using the user's name, age, and location. For example: "Hello [name], you are [age] years old and live in [location]."
Save and run the program to see the output.
"""

# Requesting user input using the input() function


name = input("Enter your name: ")
age = input("Enter your age: ")
location = input("Enter your location: ")

# To print out personalized message using the variables

print(f"Hello {name}, you are {age} years old, and live in {location}.")

